// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJqIvTse55JBrJS0ghS9kj2CRPOvdOAo',
    appId: '1:100494437835:web:a6142c53fa9efedff75a4e',
    messagingSenderId: '100494437835',
    projectId: 'autonomous-uav-c01d6',
    authDomain: 'autonomous-uav-c01d6.firebaseapp.com',
    storageBucket: 'autonomous-uav-c01d6.firebasestorage.app',
    measurementId: 'G-K2TD4BRYCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxV0_pFyJoNsb1MkDKfFMBVTTbSpjcKM',
    appId: '1:100494437835:android:7872d9abd1c11416f75a4e',
    messagingSenderId: '100494437835',
    projectId: 'autonomous-uav-c01d6',
    storageBucket: 'autonomous-uav-c01d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARTsvTj8Ijb697WRPWIiebl8c8KZg5GWI',
    appId: '1:100494437835:ios:8b0c5c7b490498a4f75a4e',
    messagingSenderId: '100494437835',
    projectId: 'autonomous-uav-c01d6',
    storageBucket: 'autonomous-uav-c01d6.firebasestorage.app',
    iosClientId: '100494437835-7ln0uf3tch2o521kv6q4mncsssfr3rfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.autonomousuav',
  );

}